sudo : required
addons:
  chrome: stable
language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run lint
 - npm run test docs --watch=false --progress=false
 - npm run test ng-write --watch=false --progress=false
 - npm run build docs 
 - npm run build ng-write