sudo : required
addons:
  chrome: stable
language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - ng test docs --watch=false --progress=false
 - ng test ng-docs --watch=false --progress=false

before_script:
  - npm install -g @angular/cli